=== api-evangelist/cloudformation/json-schema/cloudformation-change-set-detail-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ChangeSetDetail",
  "type": "object",
  "properties": {
    "ChangeSetName": {
      "type": "string"
    },
    "ChangeSetId": {
      "type": "string"
    },
    "StackId": {
      "type": "string"
    },
    "StackName": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "Parameters": {
      "type": "array"
    },
    "CreationTime": {
      "type": "string"
    },
    "ExecutionStatus": {
      "type": "string"
    },
    "Status": {
      "type": "string"
    },
    "StatusReason": {
      "type": "string"
    },
    "NotificationARNs": {
      "type": "array"
    },
    "Capabilities": {
      "type": "array"
    },
    "Tags": {
      "type": "array"
    },
    "Changes": {
      "type": "array"
    },
    "IncludeNestedStacks": {
      "type": "boolean"
    },
    "NextToken": {
      "type": "string"
    }
  }
}

=== api-evangelist/cloudformation/examples/cloudformation-change-set-detail-example.json
{
  "ChangeSetName": "example_value",
  "ChangeSetId": "500123",
  "StackId": "500123",
  "StackName": "example_value",
  "Description": "A sample description.",
  "Parameters": [],
  "CreationTime": "example_value",
  "ExecutionStatus": "example_value",
  "Status": "example_value",
  "StatusReason": "example_value",
  "NotificationARNs": [],
  "Capabilities": [],
  "Tags": [],
  "Changes": [],
  "IncludeNestedStacks": true,
  "NextToken": "example_value"
}
