=== api-evangelist/cloudformation/json-schema/cloudformation-stack-event-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "StackEvent",
  "type": "object",
  "properties": {
    "StackId": {
      "type": "string"
    },
    "EventId": {
      "type": "string"
    },
    "StackName": {
      "type": "string"
    },
    "LogicalResourceId": {
      "type": "string"
    },
    "PhysicalResourceId": {
      "type": "string"
    },
    "ResourceType": {
      "type": "string"
    },
    "Timestamp": {
      "type": "string"
    },
    "ResourceStatus": {
      "type": "string"
    },
    "ResourceStatusReason": {
      "type": "string"
    },
    "ResourceProperties": {
      "type": "string"
    },
    "ClientRequestToken": {
      "type": "string"
    },
    "HookType": {
      "type": "string"
    },
    "HookStatus": {
      "type": "string"
    },
    "HookStatusReason": {
      "type": "string"
    },
    "HookInvocationPoint": {
      "type": "string"
    },
    "HookFailureMode": {
      "type": "string"
    }
  }
}

=== api-evangelist/cloudformation/examples/cloudformation-stack-event-example.json
{
  "StackId": "500123",
  "EventId": "500123",
  "StackName": "example_value",
  "LogicalResourceId": "500123",
  "PhysicalResourceId": "500123",
  "ResourceType": "example_value",
  "Timestamp": "example_value",
  "ResourceStatus": "example_value",
  "ResourceStatusReason": "example_value",
  "ResourceProperties": "example_value",
  "ClientRequestToken": "example_value",
  "HookType": "example_value",
  "HookStatus": "example_value",
  "HookStatusReason": "example_value",
  "HookInvocationPoint": "example_value",
  "HookFailureMode": "example_value"
}
