=== api-evangelist/cloudformation/json-schema/cloudformation-stack-set-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "StackSet",
  "type": "object",
  "properties": {
    "StackSetName": {
      "type": "string"
    },
    "StackSetId": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "Status": {
      "type": "string"
    },
    "TemplateBody": {
      "type": "string"
    },
    "Parameters": {
      "type": "array"
    },
    "Capabilities": {
      "type": "array"
    },
    "Tags": {
      "type": "array"
    },
    "StackSetARN": {
      "type": "string"
    },
    "AdministrationRoleARN": {
      "type": "string"
    },
    "ExecutionRoleName": {
      "type": "string"
    },
    "PermissionModel": {
      "type": "string"
    }
  }
}

=== api-evangelist/cloudformation/examples/cloudformation-stack-set-example.json
{
  "StackSetName": "example_value",
  "StackSetId": "500123",
  "Description": "A sample description.",
  "Status": "example_value",
  "TemplateBody": "example_value",
  "Parameters": [],
  "Capabilities": [],
  "Tags": [],
  "StackSetARN": "example_value",
  "AdministrationRoleARN": "example_value",
  "ExecutionRoleName": "example_value",
  "PermissionModel": "example_value"
}
