=== api-evangelist/cloudformation/json-schema/cloudformation-type-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "TypeSummary",
  "type": "object",
  "properties": {
    "Type": {
      "type": "string"
    },
    "TypeName": {
      "type": "string"
    },
    "TypeArn": {
      "type": "string"
    },
    "DefaultVersionId": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "LastUpdated": {
      "type": "string"
    },
    "PublisherId": {
      "type": "string"
    },
    "PublisherName": {
      "type": "string"
    },
    "IsActivated": {
      "type": "boolean"
    },
    "OriginalTypeName": {
      "type": "string"
    },
    "PublicVersionNumber": {
      "type": "string"
    },
    "LatestPublicVersion": {
      "type": "string"
    }
  }
}

=== api-evangelist/cloudformation/examples/cloudformation-type-summary-example.json
{
  "Type": "example_value",
  "TypeName": "example_value",
  "TypeArn": "example_value",
  "DefaultVersionId": "500123",
  "Description": "A sample description.",
  "LastUpdated": "example_value",
  "PublisherId": "500123",
  "PublisherName": "example_value",
  "IsActivated": true,
  "OriginalTypeName": "example_value",
  "PublicVersionNumber": "example_value",
  "LatestPublicVersion": "example_value"
}
