=== api-evangelist/cloudformation/json-schema/cloudformation-change-set-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ChangeSetSummary",
  "type": "object",
  "properties": {
    "StackId": {
      "type": "string",
      "description": "The ID of the stack with which the change set is associated."
    },
    "StackName": {
      "type": "string"
    },
    "ChangeSetId": {
      "type": "string",
      "description": "The ARN of the change set."
    },
    "ChangeSetName": {
      "type": "string"
    },
    "ExecutionStatus": {
      "type": "string"
    },
    "Status": {
      "type": "string"
    },
    "StatusReason": {
      "type": "string"
    },
    "CreationTime": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "IncludeNestedStacks": {
      "type": "boolean"
    },
    "ImportExistingResources": {
      "type": "boolean"
    },
    "ParentChangeSetId": {
      "type": "string"
    },
    "RootChangeSetId": {
      "type": "string"
    }
  }
}

=== api-evangelist/cloudformation/examples/cloudformation-change-set-summary-example.json
{
  "StackId": "500123",
  "StackName": "example_value",
  "ChangeSetId": "500123",
  "ChangeSetName": "example_value",
  "ExecutionStatus": "example_value",
  "Status": "example_value",
  "StatusReason": "example_value",
  "CreationTime": "example_value",
  "Description": "A sample description.",
  "IncludeNestedStacks": true,
  "ImportExistingResources": true,
  "ParentChangeSetId": "500123",
  "RootChangeSetId": "500123"
}
