=== api-evangelist/cloudformation/json-schema/cloudformation-stack-resource-drift-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "StackResourceDrift",
  "type": "object",
  "properties": {
    "StackId": {
      "type": "string"
    },
    "LogicalResourceId": {
      "type": "string"
    },
    "PhysicalResourceId": {
      "type": "string"
    },
    "PhysicalResourceIdContext": {
      "type": "array"
    },
    "ResourceType": {
      "type": "string"
    },
    "ExpectedProperties": {
      "type": "string",
      "description": "A JSON string of the expected property values as defined in the template."
    },
    "ActualProperties": {
      "type": "string",
      "description": "A JSON string of the actual property values of the resource."
    },
    "PropertyDifferences": {
      "type": "array"
    },
    "StackResourceDriftStatus": {
      "type": "string"
    },
    "Timestamp": {
      "type": "string"
    }
  }
}

=== api-evangelist/cloudformation/examples/cloudformation-stack-resource-drift-example.json
{
  "StackId": "500123",
  "LogicalResourceId": "500123",
  "PhysicalResourceId": "500123",
  "PhysicalResourceIdContext": [],
  "ResourceType": "example_value",
  "ExpectedProperties": "example_value",
  "ActualProperties": "example_value",
  "PropertyDifferences": [],
  "StackResourceDriftStatus": "example_value",
  "Timestamp": "example_value"
}
